### ISSUE TITLE
No zoom link received for the live session

### ISSUE THREAD

**Issue by levinzx** [agu-ossi/2020-agu-oss#10]
Hi Rene, Lindsey, Leah, and Bane,

This is Xin, a participant of AGU2020-oss. I registered for the session but didn't receive the zoom link (not in SPAM either). I'm looking at the Github page and find no link to the live session. Will you please send me the link? My email is xinzhou.sys@gmail.com. Thank you very much!

Best,
Xin

**Comment by levinzx** [comment]
Never mind! Found the zoom link on the AGU session page Q&A

**Comment by lwasser** [comment]
oh good - glad you found it @levinzx i missed this issue!!
