### ISSUE TITLE
Potential source of confusion: `main` is the primary branch

### ISSUE THREAD

**Issue by banesullivan** [agu-ossi/2020-agu-oss#8]
`master` is ubiquitously used for the primary branch of a repo. This repo uses `main`. 

I suspect this could be a point of confusion for folks looking at the repo that are new to git.

It may be more trouble than it is worth resolving, but I figured I'd open the issue so we're all aware if a question about this arises.

**Comment by banesullivan** [comment]
This also makes it tougher to copy/pasta the workflow we provide:

https://github.com/agu-ossi/2020-agu-oss/blob/ec98cbed069784a68800e9710c3fb8f9888389fe/.github/workflows/docs.yml#L26

**Comment by gassmoeller** [comment]
`main` will become the new default branch for git and github over time, because of controversy around the term `master`: https://github.com/github/renaming.
I may have jumped ahead too much by renaming the branch though, if there are problems, feel free to rename back to `master` for now.

**Comment by banesullivan** [comment]
I was totally unaware of this. Let's keep it `main` then
